version: "2.4"
services:
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      #use a single node
      - discovery.type=single-node
      #ensure we do bootstrap tests
      #- es.enforce.bootstrap.checks=true
      #disable memory swapping to disk for performance
      - bootstrap.memory_lock=false
      #allow downloading from google buckets
      - repositories.url.allowed_urls=https://storage.googleapis.com/*,https://*.amazonaws.com/*
      # increase write queue size for bulk tasks
      - thread_pool.write.queue_size=1000
      # increase number of open scroll requests at a time
      - search.max_open_scroll_context=5000
    volumes:
      #use a volume for persistence / performance
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      #disable memory swapping to disk for performance
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 30s
      timeout: 500s
      retries:  30
        
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.4.0
    ports:
      - 5601:5601
    environment:
      #disable xpack as not OSS
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch

    
  mrtarget:
    image: mrtarget:latest
    build:
      context: ./
    shm_size: '4gb'
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_NODES=http://elasticsearch:9200
    tmpfs:
      - /tmp
      - /tmp:size=40G
    volumes:
      - ./log:/usr/src/app/log
      - ./json:/usr/src/app/json
      - ./qc:/usr/src/app/qc

volumes:
  esdata:
    driver: local
